apiVersion: apps/v1
kind: Deployment
metadata:
  name: auditseveritymodule
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AuditSeverityModule
  template:
    metadata:
      labels:
        app: AuditSeverityModule
    spec:
      containers:
      - name: auditseverityrepos
        image: auditchecklist.azurecr.io/auditseverityrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: auditseveritymodule
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: AuditSeverityModule